language: rust
rust:
    - stable
    - beta
sudo: false
before_script:
    - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
    - rustup component add clippy
script:
    - travis-cargo build
    - cargo build --features log
    - travis-cargo test
    - travis-cargo bench
    - travis-cargo doc
    - cargo clippy
after_success:
    - git config user.name "Travis-CI Doc Bot"
    - git config user.email "willusher.life@gmail.com"
    - travis-cargo --only stable doc-upload
env:
    global:
        secure: dtn9JgG7d2pFG/Y429JmXx4N8XsU5G6EQ7Jg2yQF6Xzq7m0jCReDVPjsIcukJqyHWiXAUUVKOpe2G86u9BRQbT6b/lPeCQxZRrEwtM1rJRqfrEJd1s4n1g7kK9H0u86IlvMXA5qEmPvyj5AcmTb+wPL4gqRxCl+hSEcSuPp7/ZQ=

